#!/bin/bash

ESC=$(printf '\033')

RESET="${ESC}[0m"

BOLD="${ESC}[1m"
UNDERSCORE="${ESC}[4m"
BLINK="${ESC}[5m"
REVERSE="${ESC}[7m"
CONCEALED="${ESC}[8m"

BLACK="${ESC}[30m"
RED="${ESC}[31m"
GREEN="${ESC}[32m"
YELLOW="${ESC}[33m"
BLUE="${ESC}[34m"
MAGENTA="${ESC}[35m"
CYAN="${ESC}[36m"
WHITE="${ESC}[37m"

BLACK_BG="${ESC}[40m"
RED_BG="${ESC}[41m"
GREEN_BG="${ESC}[42m"
YELLOW_BG="${ESC}[43m"
BLUE_BG="${ESC}[44m"
MAGENTA_BG="${ESC}[45m"
CYAN_BG="${ESC}[46m"
WHITE_BG="${ESC}[47m"

H1=${RED}
H2=${GREEN}
H3=${YELLOW}
H4=${BLUE}
H5=${MAGENTA}
H6=${CYAN}

sed -E "s/^(# .*)/${H1}\1${RESET}/" \
| sed -E "s/^(## .*)/${H2}\1${RESET}/" \
| sed -E "s/^(### .*)/${H3}\1${RESET}/" \
| sed -E "s/^(#### .*)/${H4}\1${RESET}/" \
| sed -E "s/^(##### .*)/${H5}\1${RESET}/" \
| sed -E "s/^(###### .*)/${H6}\1${RESET}/"

