#!/bin/bash

ESC=$(printf '\033')

RESET="${ESC}[0m"

BLACK="${ESC}[30m"
RED="${ESC}[31m"
GREEN="${ESC}[32m"
YELLOW="${ESC}[33m"
BLUE="${ESC}[34m"
MAGENTA="${ESC}[35m"
CYAN="${ESC}[36m"
WHITE="${ESC}[37m"

H1=${RED}
H2=${GREEN}

sed -E "s/^(# .*)/${H1}\1${RESET}/" \
| sed -E "s/^(## .*)/${H2}\1${RESET}/"

